package com.arcieri.wagner.mvvm_recipebook.utils

import com.arcieri.wagner.mvvm_recipebook.presentation.ui.theme.*

val colorList_1_4 = listOf(
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Black_25,
    RB_Black_50,
    RB_Black_75,
    RB_Black_90,
    RB_Black,
)

val colorList_1_5 = listOf(
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Black_25,
    RB_Black_50,
    RB_Black_75,
    RB_Black_90,
    RB_Black,
)

val colorList_1_6 = listOf(
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Black_25,
    RB_Black_50,
    RB_Black_75,
    RB_Black_90,
    RB_Black,
)

val colorList_1_4_2blacks = listOf(
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Black_25,
    RB_Black_50,
    RB_Black_75,
    RB_Black_90,
    RB_Black,
    RB_Black,
)

val colorList_1_4_3blacks = listOf(
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Transparent,
    RB_Black_25,
    RB_Black_50,
    RB_Black_75,
    RB_Black_90,
    RB_Black,
    RB_Black,
    RB_Black,
)